# Generated by Django 3.0.8 on 2020-10-20 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Food', 'Food'), ('Clothes', 'Clothes')], max_length=200)),
                ('type_food', models.CharField(choices=[('Veg', 'Veg'), ('NonVeg', 'Nonveg'), ('Both', 'Both')], max_length=200, null=True)),
                ('pickup_location', models.CharField(max_length=200, null=True)),
                ('food_fresh', models.FloatField(null=True)),
                ('served_people', models.FloatField(null=True)),
                ('clothes_no', models.FloatField(null=True)),
                ('agegroup', models.CharField(choices=[('0-5', '0-5'), ('5-13', '5-13'), ('13-20', '13-20'), ('20-30', '20-30'), ('30-50', '30-50'), ('50+', '50+')], max_length=200)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
