# Generated by Django 3.0.8 on 2020-11-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_organizations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='agegroup',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='clothes_no',
        ),
        migrations.AddField(
            model_name='posts',
            name='Phone',
            field=models.FloatField(null=True),
        ),
    ]
