# Generated by Django 3.0.8 on 2020-11-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20201104_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='Phone',
            field=models.IntegerField(null=True),
        ),
    ]
