# Generated by Django 3.0.8 on 2020-11-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20201104_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='agegroupofclothes',
            field=models.CharField(blank=True, choices=[('0-5', '0-5'), ('5-12', '5-12'), ('12-20', '12-20'), ('20-30', '20-30'), ('30-50', '30-50'), ('50+', '50+')], max_length=200),
        ),
        migrations.AlterField(
            model_name='posts',
            name='food_fresh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='type_food',
            field=models.CharField(blank=True, choices=[('Veg', 'Veg'), ('NonVeg', 'Nonveg'), ('Both', 'Both')], max_length=200, null=True),
        ),
    ]
